# SPDX-FileCopyrightText: James Turner <james@flightgear.org>
# SPDX-License-Identifier: GPL-2.0-or-later

spec:
  inputs:
    clear-ccache-cache:
      type: boolean
      default: false
      description: "Clear the 'ccache' cache before starting the builds"

    simgear-ref:
      default: next
      description: "Git ref of the 'simgear' artifacts to fetch"

    fgdata-ref:
      default: next
      description: >
        Git ref of the 'fgdata' artifacts to fetch for running the test suite

    openscenegraph-ref:
      default: next
      description: "Git ref of the 'openscenegraph' artifacts to fetch"
---

variables:
  LC_CTYPE: C.UTF-8
  BUILD_DIR: "$CI_PROJECT_DIR/build"
  PREFIX_DIR: "$CI_PROJECT_DIR/dist"
  # cache:key is not allowed to contain '/' characters
  BRANCH_REF_SLUG: next
  # create a root dir *above* the Simgear checkout, otherwise CMake
  # complains about INTERFACE_INCLUDE_DIRECTORIES being the source dir
  WIN_FG_DIR: $CI_BUILDS_DIR\flightgear
  MAC_IMAGE: macos-26-xcode-26

# do not run pipelines on forks
# build merge requests, tags and the protected branches
workflow:
  rules:
    - if: $CI_PROJECT_NAMESPACE != "flightgear"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

# There is an example at https://pre-commit.com/#gitlab-ci-example
.pre-commit-common:
  stage: build
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/pre-commit:latest
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    key: pre-commit
    paths:
      - ${PRE_COMMIT_HOME}

# This job runs only on MR branches and needs to pass.
pre-commit-merge:
  extends: .pre-commit-common
  script:
    - git fetch origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - >
      pre-commit run --from-ref origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
      --to-ref "$CI_COMMIT_SHA"
    - git-clang-format --diff origin/"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

pre-commit:
  extends: .pre-commit-common
  script:
    # Run on all files. We're quite far from this being error-free, so report
    # success despite reality. This way, the pipeline status can be used to
    # monitor jobs we're actively trying to keep in working state.
    - pre-commit run --all-files || true
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.ccache-variables:
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}/ccache-cache
    # This allows one to obtain ccache stats for a single job.
    CCACHE_STATSLOG: ${CI_PROJECT_DIR}/ccache-stats.log

.ccache-pre_non-windows:
  before_script:
    # Optional clearing of the 'ccache' cache
    - |
      if $[[ inputs.clear-ccache-cache ]]; then
        echo "Clearing the 'ccache' cache"
        ccache --clear
      fi
    - rm -f $CCACHE_STATSLOG

.ccache-pre_windows:
  before_script:
    # Optional clearing of the 'ccache' cache
    - |
      if ('$[[ inputs.clear-ccache-cache ]]' -eq 'true') {
        echo 'Clearing the ''ccache'' cache'
        ccache --clear
      }
    - |
      if (Test-Path $CCACHE_STATSLOG) {
        Remove-Item -Path $CCACHE_STATSLOG
      }

.ccache-stats:
  after_script:
    # For the particular build recorded in ${CCACHE_STATSLOG}
    - ccache --show-log-stats
    # Shows how much of the configurable cache size is used
    - ccache --show-stats

linux-build:
  extends: .ccache-variables
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear:latest
  stage: build
  before_script:
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    # --fresh would be ideal here to avoid this line, but needs CMake 3.24
    - rm -f $BUILD_DIR/CMakeCache.txt

    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D ENABLE_FGQCANVAS=ON
      -D CMAKE_PREFIX_PATH="$CI_PROJECT_DIR/simgear-dist;$CI_PROJECT_DIR/osg-dist"
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target fgfs_test_suite
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  artifacts:
    when: on_success
    paths:
      - $PREFIX_DIR
      # This is needed for the 'test' job.
      - $BUILD_DIR/test_suite
  needs:
    - project: flightgear/simgear
      job: linux-build
      artifacts: true
      ref: $[[ inputs.simgear-ref ]]
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $[[ inputs.openscenegraph-ref ]]
      artifacts: true
  cache:
    key: linux-amd64-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

linux-qt5-build:
  extends: .ccache-variables
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear-qt5:latest
  stage: build
  before_script:
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    # --fresh would be ideal here to avoid this line, but needs CMake 3.24
    - rm -f $BUILD_DIR/CMakeCache.txt

    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_PREFIX_PATH="$CI_PROJECT_DIR/simgear-dist;$CI_PROJECT_DIR/osg-dist"
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/simgear
      job: linux-qt5-build
      artifacts: true
      ref: $[[ inputs.simgear-ref ]]
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $[[ inputs.openscenegraph-ref ]]
      artifacts: true
  cache:
    key: linux-amd64-qt5-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

canvas-pi-build:
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/fgqcanvas-raspbian:latest
  stage: build
  script:
    - dpkg -s qt6-declarative-dev
    - dpkg -L qt6-declarative-dev
    - ls -l /usr/lib/aarch64-linux-gnu/cmake/Qt6Quick/Qt6QuickConfig.cmake
    - head /usr/lib/aarch64-linux-gnu/cmake/Qt6Quick/Qt6QuickConfig.cmake
    - tail /usr/lib/aarch64-linux-gnu/cmake/Qt6Quick/Qt6QuickConfig.cmake

    # Explicitly set Qt6DBus_DIR to avoid intermittent failures to configure.
    # Sometimes, find_package( Qt6 COMPONENTS Gui ....) fails to search
    # the package subdir for Qt6DBusConfig.cmake, so configuration fails.
    - >
      cmake --fresh -B $BUILD_DIR -S $CI_PROJECT_DIR/utils/fgqcanvas -G Ninja
      --debug-find-pkg=Qt6Quick
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CHECK_FOR_QT5=OFF
      -D Qt6DBus_DIR=/usr/lib/aarch64-linux-gnu/cmake/Qt6DBus

    - cmake --build $BUILD_DIR --target install

    # produce a .DEB
    - cpack -G DEB -B _packages --config $BUILD_DIR/CPackConfig.cmake

  artifacts:
    paths:
      - _packages

  allow_failure: true

windows-build:
  variables:
    CCACHE_DIR: ${CI_PROJECT_DIR}\ccache-cache
    CCACHE_STATSLOG: ${CI_PROJECT_DIR}\ccache-stats.log
  stage: build
  tags:
    - saas-windows-medium-amd64
  before_script:
    - C:\"Program Files (x86)\Microsoft Visual Studio"\2022\BuildTools\Common7\Tools\Launch-VsDevShell -SkipAutomaticLocation -Arch amd64
    # relocate our upstream deps outside the source dir, otherwise
    # CMake gets sad.
    - Move-Item -Path $CI_PROJECT_DIR\boost $WIN_FG_DIR\boost
    - Move-Item -Path $CI_PROJECT_DIR\msvc140 $WIN_FG_DIR\msvc140
    # Should ideally be done inside CMake but this works for now.
    # The addition of $CI_PROJECT_DIR is for ccache.exe.
    - $Env:PATH += ";$WIN_FG_DIR\msvc140\3rdparty.x64\bin;$CI_PROJECT_DIR"
    - !reference [.ccache-pre_windows, before_script]
  script:
    - >
      cmake -B $env:BUILD_DIR -S $env:CI_PROJECT_DIR -G "Ninja Multi-Config"
      --fresh
      -D CMAKE_INSTALL_PREFIX=$env:PREFIX_DIR
      -D MSVC_3RDPARTY_ROOT=$WIN_FG_DIR
      -D OSG_FSTREAM_EXPORT_FIXED:BOOL=ON
      -D CMAKE_PREFIX_PATH="$env:CI_PROJECT_DIR\simgear-dist;$env:CI_PROJECT_DIR\osg-dist"
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR --config Release
    - cmake --build $BUILD_DIR --config Release --target install
  after_script:
    # This is needed for ccache.exe.
    - $Env:PATH += ";$CI_PROJECT_DIR"
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/simgear
      job: windows-build
      ref: $[[ inputs.simgear-ref ]]
      artifacts: true
    - project: flightgear/openscenegraph
      job: windows_build
      ref: $[[ inputs.openscenegraph-ref ]]
      artifacts: true
    - project: flightgear/windows-3rd-party
      job: windows_build_msvc140
      ref: master
      artifacts: true
  artifacts:
    paths:
      - dist
  cache:
    key: windows-amd64-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

macos-build:
  stage: build
  extends: .ccache-variables
  tags:
    - saas-macos-medium-m1
  image: $MAC_IMAGE
  before_script:
    - export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
    - export HOMEBREW_NO_INSTALL_CLEANUP=1
    - brew install ninja cmake boost nlohmann-json ccache
    - !reference [.ccache-pre_non-windows, before_script]
  script:
    # ensure we use our FreeType and not the one from Homebrew
    # ours is UB, HomeBrew's is not
    - export FREETYPE_DIR=$CI_PROJECT_DIR/dist
    - >
      cmake -B $BUILD_DIR -S $CI_PROJECT_DIR -G Ninja
      --fresh
      -D CMAKE_BUILD_TYPE=RelWithDebInfo
      -D CMAKE_INSTALL_PREFIX=$PREFIX_DIR
      -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"
      -D CMAKE_PREFIX_PATH="$CI_PROJECT_DIR/osg-dist;$CI_PROJECT_DIR/simgear-dist"
      -D ENABLE_CCACHE=ON

    - cmake --build $BUILD_DIR
    - cmake --build $BUILD_DIR --target install
  after_script:
    - !reference [.ccache-stats, after_script]
  needs:
    - project: flightgear/simgear
      job: macos-build
      ref: $[[ inputs.simgear-ref ]]
      artifacts: true
    - project: flightgear/openscenegraph
      job: macos-build
      ref: $[[ inputs.openscenegraph-ref ]]
      artifacts: true
    - project: flightgear/macos-3rd-party
      job: macos-build
      ref: main
      artifacts: true
  artifacts:
    paths:
      - dist
  cache:
    key: macos-universal-$BRANCH_REF_SLUG
    paths:
      - $CCACHE_DIR

test:
  image: ${CI_REGISTRY}/flightgear/flightgear-ci-docker/flightgear:latest
  stage: test
  script:
    - cd $BUILD_DIR
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CI_PROJECT_DIR/osg-dist/lib
    - ./test_suite/fgfs_test_suite --fg-root $CI_PROJECT_DIR/testFGData --junit
  needs:
    - job: linux-build
      artifacts: true
    - project: flightgear/fgdata
      job: create-test-data
      ref: $[[ inputs.fgdata-ref ]]
      artifacts: true
    - project: flightgear/openscenegraph
      job: linux-build
      ref: $[[ inputs.openscenegraph-ref ]]
      artifacts: true
  artifacts:
    # Note that the artifacts in artifacts:reports are _always_ uploaded,
    # even for failed jobs (special rule).
    paths:
      - $BUILD_DIR/FGData_tests_junit.xml
      - $BUILD_DIR/Simgear_unit_tests_junit.xml
      - $BUILD_DIR/System_tests_junit.xml
      - $BUILD_DIR/Unit_tests_junit.xml
    reports:
      junit: $BUILD_DIR/*_junit.xml
